### ISSUE TITLE
JavaScript Capstone Project

### ISSUE THREAD

**Issue by usmansbk** [usmansbk/javascript-capstone#21]
Project Link: https://github.com/usmansbk/javascript-capstone/projects/1

This project is comprised of two members:

1. Usman - @usmansbk 
2. Tolib - @toliboff

**Comment by abruzy** [comment]
Hi @usmansbk & @toliboff 👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
